name: JSON Lint

on:
  push:
    paths:
      - "dict.json"
  pull_request:
    paths:
      - "dict.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate JSON
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          jq . dict.json > /dev/null
